### ISSUE TITLE
Trigger "onCancel" when user presses esc while editing Post/Comment

### ISSUE THREAD

**Issue by essential-randomness** [BobaBoard/boba-components#79]

**Comment by scumsuck** [comment]
this is a big one for me LOL i can never find the cancel button even though it's right there :p

**Comment by essential-randomness** [comment]
I feel like https://github.com/BobaBoard/boba-frontend/issues/78 will probably help (since it would make the cancel/post buttons blend together less).

Anyway, totally going to happen in the next month! Be excite.

**Comment by essential-randomness** [comment]
Closed by #107
