### ISSUE TITLE
Fix square of empty space on the header when sidemenu is open

### ISSUE THREAD

**Issue by essential-randomness** [BobaBoard/boba-components#84]
There is square of empty space between the BOBABOARD logo and the sidemenu that opens up. There should not be a square of empty space.

To fix as part of https://github.com/BobaBoard/issues/discussions/98

**Comment by riazaia** [comment]
A visual aid :3

![image](https://user-images.githubusercontent.com/42520601/192669573-6b25c58c-7656-4432-9a66-d3897bb07bcd.png)

**Comment by essential-randomness** [comment]
Fixed by: https://github.com/BobaBoard/boba-components/pull/95
